### ISSUE TITLE
0.3.6 release needs patching due to bug on chipsets with AVX512 instructions

### ISSUE THREAD

**Issue by stuartarchibald** [AnacondaRecipes/openblas-feedstock#4]
Issue:

The 0.3.6 release seemingly has a problem in the GEMM kernels for double precision input on AVX512 capable chips. See https://github.com/numba/numba/pull/4273#issuecomment-509617580, seems like this needs https://github.com/xianyi/OpenBLAS/pull/2111 applying. Patch from conda-forge is here: https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/gh2111.patch

CC @soapy1 as committer for 0.3.6 build.

**Comment by jjhelmus** [comment]
The latest build of openblas in `defaults` includes the patch from the `conda-forge` recipe for AVX512/SkylakeX kernels.

**Comment by stuartarchibald** [comment]
Thanks @jjhelmus
